# Generated by Django 3.0.5 on 2020-07-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200708_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='when',
            field=models.CharField(default='tbd', max_length=10),
        ),
    ]
